#Site settings
title: NS쇼핑 기술 블로그
email: skyksit@nsmall.com
description: |
  삶의 가치 창출과 행복나눔
baseurl: ''
url: 'http://BlueWings2017.github.io'
timezone: Asia/Seoul

encoding: utf-8
highlighter: rouge
#highlighter: pygments

repository: nsshopping/nsshopping.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

sass:
  add_charset: true

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

# paging
paginate: 10
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]
github: [metadata]
#custom
author: skyksit@nsmall.com
image: '/assets/images/default_blog_cover.jpg'
ogimage: '/assets/images/default_blog_ogimage.jpg'
asset_url: /assets

#google_analytics:
#  ua: 'UA-108295858-1'
facebook:
  username: NSshopping
#google_plus:
#  username:
github_url:
  username: nsshopping
google_tag:
  ua: GTM-NZ7M7K3

# Disqus
discus-identifier: ns-github-io # add your discus identifier
